# .yarnrc.yml

# This path specifies which version of Yarn to use for this project.
yarnPath: ".yarn/releases/yarn-3.6.3.cjs"

# Disable immutability checks (like frozen lockfile)
enableImmutableInstalls: false
